# Workflow for validating pull requests
name: Validation

# Triggers the workflow on push or pull request for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# This workflow is made up of three jobs: build, lint, and test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Check if this job should continue
        id: continue
        run: |
          git diff --exit-code -- build/ src/ *.json yarn.lock || echo ::set-output name=CONTINUE::true
      - name: Setup node.js
        if: steps.continue.outputs.CONTINUE
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          check-latest: true
      - name: Install dependencies
        if: steps.continue.outputs.CONTINUE
        run: yarn install --frozen-lockfile --production
      - name: Build app
        if: steps.continue.outputs.CONTINUE
        run: yarn build --frozen-lockfile

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Check if this job should continue
        id: continue
        run: |
          git diff --exit-code -- '***js' '***jsx' '***ts' '***tsx' package.json yarn.lock || echo ::set-output name=CONTINUE::true
      - name: Setup node.js
        if: steps.continue.outputs.CONTINUE
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          check-latest: true
      - name: Install dependencies
        if: steps.continue.outputs.CONTINUE
        run: yarn install --frozen-lockfile
      - name: Lint
        if: steps.continue.outputs.CONTINUE
        run: yarn lint

  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          check-latest: true
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Style
        run: yarn prettier --check .

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Check if this job should continue
        id: continue
        run: |
          git diff --exit-code -- src/ *.json yarn.lock || echo ::set-output name=CONTINUE::true
      - name: Setup node.js
        if: steps.continue.outputs.CONTINUE
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          check-latest: true
      - name: Install dependencies
        if: steps.continue.outputs.CONTINUE
        run: yarn install --frozen-lockfile
      - name: Run tests
        if: steps.continue.outputs.CONTINUE
        run: yarn test
